name: brdz_test
description: "Brdz Test project"
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  collection: ^1.16.0
  cryptography: ^2.7.0
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  flutter_secure_storage: ^8.0.0
  freezed_annotation: ^2.2.0
  go_router: ^12.1.3
  hive_flutter: ^1.1.0
  http_parser: ^4.0.2
  intl: ^0.20.2
  json_annotation: ^4.8.0
  mobile_scanner: ^7.1.3
  walletconnect_dart: ^0.0.11
  web3dart: ^2.7.1
  url_launcher: ^6.2.1


dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1


flutter:
  generate: true
  uses-material-design: true
#  assets:
#    - assets/icons/
#    - assets/images/
#    - assets/fonts/
